[grid]
begin = 0
end = 6

[inventory]
money = 0

[[tiles]]
q = 1
r = 1
content = "player"
hp = 10
weapon = "axe"

[[tiles]]
q = 3
r = 2
content = "enemy"
hp = 8
weapon = "sword"

[[tiles]]
q = 4
r = 3
content = "enemy"
hp = 8
weapon = "bow"

[[tiles]]
q = 2
r = 3
content = "house"
hp = 10

[[tiles]]
q = 5
r = 5
content = "boat"

[[tiles]]
q = 0
r = 5
terrain = "water"

[[tiles]]
q = 1
r = 5
terrain = "water"

[[tiles]]
q = 0
r = 6
terrain = "water"

[[tiles]]
q = 1
r = 6
terrain = "water"

[[tiles]]
q = 2
r = 6
terrain = "water"

[[tiles]]
q = 6
r = 5
terrain = "water"

[[tiles]]
q = 6
r = 6
terrain = "water"

[[tiles]]
q = 5
r = 6
terrain = "water"
